#!/bin/sh
APPDIR=`dirname $0`;
java  -Xmx256M -cp "$APPDIR/src:$APPDIR/bin:/home/abossy/tools/gwt-linux-1.5.2/gwt-user.jar:/home/abossy/tools/gwt-linux-1.5.2/gwt-dev-linux.jar" com.google.gwt.dev.GWTCompiler -style PRETTY -out "/home/abossy/projects/fitness/site_media/" "$@" com.healthySoftware.fitnessUI;
