#!/bin/sh
APPDIR=`dirname $0`;
java -XstartOnFirstThread -Dgwt.args="-web -out www-test" -Xmx256M -cp "$APPDIR/src:$APPDIR/test:$APPDIR/bin:/Users/adambossy/Downloads/eclipse/plugins/org.junit_3.8.2.v20080602-1318/junit.jar:/Users/adambossy/Documents/workspace/gwt-mac-1.5.3/gwt-user.jar:/Users/adambossy/Documents/workspace/gwt-mac-1.5.3/gwt-dev-mac.jar" junit.textui.TestRunner com.healthySoftware.client.AddWorkoutTest "$@";
