#!/bin/sh
APPDIR=`dirname $0`;
java -XstartOnFirstThread -Xmx256M -cp "$APPDIR/src:$APPDIR/bin:/Users/adambossy/Documents/workspace/gwt-mac-1.5.3/gwt-user.jar:/Users/adambossy/Documents/workspace/gwt-mac-1.5.3/gwt-dev-mac.jar" com.google.gwt.dev.GWTShell -out "$APPDIR/www" "$@" http://localhost:8000/workout/add_workout/1/ -noserver;
