#!/bin/sh
APPDIR=`dirname $0`;
java -XstartOnFirstThread -Xmx256M -cp "$APPDIR/src:$APPDIR/bin:/Users/adambossy/Documents/workspace/gwt-mac-1.5.3/gwt-user.jar:/Users/adambossy/Documents/workspace/gwt-mac-1.5.3/gwt-dev-mac.jar" com.google.gwt.dev.GWTCompiler -out "$APPDIR/www" "$@" com.healthySoftware.AddWorkout;
